all: lab1-01 lab1-02 lab1-execvp lab1-execlp lab1-waitpid lab1-nowait lab1-readproc

lab1-01: lab1-01.c
	gcc $^ -o $@ -Wall

lab1-02: lab1-02.c
	gcc $^ -o $@ -Wall
	
lab1-execvp: lab1-execvp.c
	gcc $^ -o $@ -Wall

lab1-execlp: lab1-execlp.c
	gcc $^ -o $@ -Wall

lab1-waitpid: lab1-waitpid.c
	gcc $^ -o $@ -Wall

lab1-nowait: lab1-nowait.c
	gcc $^ -o $@ -Wall

lab1-readproc: lab1-readproc.c
	gcc $^ -o $@ -Wall

clean:
	rm -f lab1-01 lab1-02 lab1-execvp lab1-execlp lab1-waitpid lab1-nowait lab1-readproc
